---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: resource01s.group01.project01.com
spec:
  group: group01.project01.com
  names:
    kind: Resource01
    plural: resource01s
    singular: resource01
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              field01:
                type: integer
              field02:
                type: string